### ISSUE TITLE
username koymak orijinal mojang kurallarına göre olsun

### ISSUE THREAD

**Issue by ghost** [Mehmetali345Dev/345-Launcher#2]
bu öneriyi yapmak istedim bakılırsa sevinirim
- İsimler 2 harfden oluşması zorunludur
- İsimlerde boşluk kullanılmamalıdır
- Türkçe harf olmamalıdır
ve daha fazlası

**Comment by Mehmetali345Dev** [comment]
Dikkate alacağım yeni sürümde bugfix yapılacaktır. Ancak lütfen bundan sonra issueleri İngilizce açmaya özen gösterin.
