### ISSUE TITLE
Skin Ekleme

### ISSUE THREAD

**Issue by Salih-Berat** [Mehmetali345Dev/345-Launcher#3]
Oyuna başlarken mcskinin (başka bir site de olabilir premium oyuncuların skinini göstersin yeter işte) skin deposundaki kullanıcı skinleri gösterilip seçtirilebilir. Seçilen skin oyunun steve veya Alex skininin yerine geçer ve oyuncu o skinle oynar. (Çok oyunculuda sadece kendisini o skinle görür diğer oyuncular onu steve olarak görür. Tek oyunculuda zaten tek skini o skin olmuş olur.)

**Comment by Mehmetali345Dev** [comment]
Mantıklı ancak Launcher Premiumlu değil o yüzden daha eklemeye gerek yok.
