### ISSUE TITLE
345 Kurulduğu zaman ram verilme sorunu

### ISSUE THREAD

**Issue by Salih-Berat** [Mehmetali345Dev/345-Launcher#4]
![ram sorunu](https://user-images.githubusercontent.com/70946597/116535291-4519d080-a8ec-11eb-9805-c6051a33dd26.PNG)
345 Launcher kurulduğu zaman ram böyle verilmiş gözüküyor buradaki yazılar ya değiştirilmeli ya da ram verme değerleri tam tersi olmalı.

**Comment by Mehmetali345Dev** [comment]
Sorun çözüldü şimdiki kod düzeltmede yayınlanacak.

**Comment by Mehmetali345Dev** [comment]
Ayrıca yeni sürüme düzeltildi.
