### ISSUE TITLE
Launcher'a Hazır Mod Paketi Ekleme

### ISSUE THREAD

**Issue by Salih-Berat** [Mehmetali345Dev/345-Launcher#5]
Çoğu kişi sodium, phosphor gibi modları bilmiyor ve 1.16.5 gibi sürümleri bu yüzden oynayamıyor launcherda optimizasyon sağlayacak modlar bir araya getirilip sol altta nasıl 1.16.5 gibi giriş yazıyorsa 1.16.5-Optimizasyonlu gibi giriş seçenekleri otomatik olarak kurulu gelebilir. Yada grafik sevdalılarına Optifine'ın bütün her şeyini Ultra haline getirip 1.16.5-YüksekKalite gibi şeyler gelebilir.

**Comment by bynoment** [comment]
FTP Den modları otomatik çektirip indirtebiliriz. iyi olur

**Comment by Mehmetali345Dev** [comment]
Launcher'ı uzun zaman önce geliştirmeyi bıraktım. Yenilenmiş, electron veya tauri ile yazılmış hali bir gün belki gelir. O zaman modrinth desteğide sunmayı planlıyorum.
