### ISSUE TITLE
Güncelleme Konumunu Görememek

### ISSUE THREAD

**Issue by Salih-Berat** [Mehmetali345Dev/345-Launcher#7]
![dosya konumunu nerden bulcaz](https://user-images.githubusercontent.com/70946597/116560158-c9c71780-a909-11eb-9ebf-9dffcc47d561.PNG)
345 Launcher'i güncellediğimizde nereye indirdiğini bilmiyoruz. Launcher'da nereye indireceğimiz seçilebilmeli veya nereye ineceği yazılmalı.

**Comment by Mehmetali345Dev** [comment]
Dikkatli oku orada Dosya Launcherın bulunduğu yere indirilecektir yazıyor.
