### ISSUE TITLE
chrome abi iş başında

### ISSUE THREAD

**Issue by DomatesGames** [Mehmetali345Dev/345-Launcher#8]
kalitrik'i takip ediyorum bildirim geldi de geldim baktım biraz. https://launcher.mehmetali345.xyz/ 'de indirince chrome virüs algılıyor, ya gerçekten virüslenmiş ya da chrome'un alerjisi var

**Comment by Mehmetali345Dev** [comment]
Evet o konu birazcık gıcık sebebi ise kod imzalama sertifikası olmaması ama bundan sonraki update sertifika içerecek.
